### ISSUE TITLE
使用反射创建SharedMemory失败

### ISSUE THREAD

**Issue by zongren** [rabbitknight/OpenMemory#1]
下面的代码抛出异常
`Class<?> c = Class.forName("android.os.SharedMemory");`
`Object sharedMemory = InvokeUtil.newInstanceOrThrow(c, fd);`

`throw new IllegalArgumentException("Can't get even one available constructor for " + clz);`

然后我看到android 27及以上用的SharedMemory而不是MemoryFile

**Comment by rabbitknight** [comment]
[root cause]
1. 初步判断为MemoryFileHolder 中对于 SDK的判断问题。
2. 确实，只要>=API 27 对于MemoryFile的反射就收到系统限制，同时系统提供了SharedMemory 来取代相关实线。
[solution]
1. 可以尝试将所有`Build.VERSION.SDK_INT > Build.VERSION_CODES.O_MR1` 替换为 `Build.VERSION.SDK_INT >=Build.VERSION_CODES.O_MR1`

感谢！

**Comment by zongren** [comment]
ok，多谢
